### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless compression.

### CODE REVIEW

**Comment by KosmX** [comment]
Apparently, Imgbot did a better job than oxipng.  
Also, I don't want to optimize non-resource files. `blend and other files`  
  
I'll check this compression myself.

**Comment by KosmX** [comment]
Yours is better.  
Please create another PR without modifying `blend and other files` and I'll merge that.  
Or I may do it myself

**Comment by K0-RR** [comment]
Sure, I will do it but may I ask why not `blend and other files`? The compression was lossless so I don't see any drawbacks. Is it about stripped metadata?

Btw the command was `oxipng -o max -s full -r --fix -t 8 -Z` (forgot about -p back then to preserve attributes).

**Comment by K0-RR** [comment]
Also, the logo that is included in the jar is huge - 1024x1024. Are you sure you don't want to crop it to like 512x? It still would be huge considering it's only for ModMenu. When done alongside reducing the color palette the size dropped to 28.2 kB (-93%) and I can't see any visual differences.

**Comment by K0-RR** [comment]
512x512 with reduced colors to 256. (Github does not compress attachments, right?)
emotecraft_mod_logo

**Comment by KosmX** [comment]
Do we even need 512x512 res? On my laptop with 1080p res, The icon's max size is 128x128. On a 4K monitor, it can be 256x256.  
The user needs a 16K TV/Monitor to reach 512x512 with max GUI size. but Do people play with that UI size?  
I think a 256x256 icon size is enough.  
But using only 256 colors is not needed. As I know, PNG can compress colors well.

**Pull request closed without merging**
